### ISSUE TITLE
pip installed refl1d on Windows requires Python38.dll

### ISSUE THREAD

**Issue by hoogerheide** [reflectometry/refl1d#125] opened 2021-06-04 18:24 UTC
When installing refl1d on Windows using pip (I'm using an Anaconda distribution), reflmodule.pyd is linked directly to Python38.dll. This is true even if the python version used for the pip installation is 3.7, which then breaks reflmodule, raising an "ImportError: DLL not found" exception.

Note that installing refl1d under Python 3.8 allows import of reflmodule, but if a specific version of Python is required to run refl1d, this should perhaps be a dependency (or perhaps relaxed -- is there any reason to not allow 3.7, for example?)

**Comment by pkienzle** [comment] 2021-06-04 19:14
It shouldn't. Here's the link line:
```
2021-05-30T17:58:31.5250583Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\hostedtoolcache\windows\Python\3.8.10\x64\libs /LIBPATH:C:\hostedtoolcache\windows\Python\3.8.10\x64\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" /EXPORT:PyInit_reflmodule build\temp.win-amd64-3.8\Release\refl1d\lib\reflmodule.obj build\temp.win-amd64-3.8\Release\refl1d\lib\methods.obj build\temp.win-amd64-3.8\Release\refl1d\lib\reflectivity.obj build\temp.win-amd64-3.8\Release\refl1d\lib\magnetic.obj build\temp.win-amd64-3.8\Release\refl1d\lib\contract_profile.obj build\temp.win-amd64-3.8\Release\refl1d\lib\convolve.obj build\temp.win-amd64-3.8\Release\refl1d\lib\convolve_sampled.obj /OUT:build\lib.win-amd64-3.8\refl1d\reflmodule.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\refl1d\lib\reflmodule.lib
```
Simplified so it's easier to see that there are not refs to a python dll:
```
link.exe /nologo ... /EXPORT:PyInit_reflmodule reflmodule.obj methods.obj ... /OUT:reflmodule.pyd /IMPLIB:reflmodule.lib
```
Or any python libs for that matter. That's a bit surprising. I guess they use header magic to do all the version-independent binding inline rather than calling out to functions to do so.

One possibility is the version on pypi is out of date, and we did the version independent change since last release (though I don't think so).

Can you please download Dependency Walker and check what the .pyd in the windows wheel file references? This should tell us whether the python version is hard-coded into the package.

Another possibility is that there is an indirect reference to a python dll, and it is picking the first one up on the library path regardless of where it is, while a different version is on your command path.

**Comment by hoogerheide** [comment] 2021-06-04 19:54
I originally used https://github.com/lucasg/Dependencies to find the Python38.dll dependency. I will check whether a fresh Python 3.7 environment has this problem too.

![image](https://user-images.githubusercontent.com/14282356/120855845-001d3580-c54d-11eb-94d9-2c8b6426b199.png)

**Comment by hoogerheide** [comment] 2021-06-04 20:01
Confirming that this fails with a fresh Python 3.7 environment. After creating the new environment (Python 3.7.10), I simply ran "conda install matplotlib numpy scipy" and then "pip install refl1d".

**Comment by bmaranville** [comment] 2021-06-04 21:36
I was able to reproduce in a python.org environment for python3.7.9 and python3.9.x

I found an issue online that suggests maybe we should define Py_LIMITED_API in our lib files before including Python.h, which strangely we don't seem to be doing (there is a line, but it is commented out).

I thought I had uncommented those lines?

https://github.com/pypa/pip/issues/4445#issuecomment-377680803
[https://avatars2.githubusercontent.com/u/647025?s=400&v=4]<https://github.com/pypa/pip/issues/4445#issuecomment-377680803>
Windows Stable ABI Support · Issue #4445 · pypa/pip · GitHub<https://github.com/pypa/pip/issues/4445#issuecomment-377680803>
Pip version: 9.0.1 Python version: Any py3 Operating system: Windows Description: I'd like to be able to use the stable ABI to lessen the burden of distributing wheels. pip 9 supports this on macOS, but on Windows it does not. The stable...
github.com

________________________________

**Comment by bmaranville** [comment] 2021-06-04 21:44
https://www.python.org/dev/peps/pep-0384/#the-buffer-interface
[https://www.python.org/static/opengraph-icon-200x200.png]<https://www.python.org/dev/peps/pep-0384/#the-buffer-interface>
PEP 384 -- Defining a Stable ABI | Python.org<https://www.python.org/dev/peps/pep-0384/#the-buffer-interface>
Rationale. The primary source of ABI incompatibility are changes to the lay-out of in-memory structures. For example, the way in which string interning works, or the data type used to represent the size of an object, have changed during the life of Python 2.x.
www.python.org
It would seem the buffer interface is not included in the limited API.  Hmm...
________________________________

**Comment by pkienzle** [comment] 2021-06-04 21:47
I can see the python38.dll in reflmodule.pyd from the windows wheel downloaded from pypi. I still don't understand how it got there since there are no references on the link line. I also skimmed through the python imports but didn't find anything obvious that would lead to an implicit link to the dll.

It may be that the link line has changed since Feb. and the next release will fix the problem. I couldn't figure out how to retrieve the build artifacts from github actions to check.

I guess try the Py_LIMITED_API change and see if the problem fixes itself?

BTW, I was able to use "strings reflmodule.pyd | grep -i dll" to see that it was linked.

**Comment by bmaranville** [comment] 2021-06-04 21:57
The artifacts from the build are all expired and github threw them away, but the wheel files in the release should be the same ones on pypi, are they not?
________________________________

**Comment by pkienzle** [comment] 2021-06-04 22:16
The question is whether the link line has changed since the release. Looking at the build logs I don't see how the python38.dll is getting linked in, but it is clearly there in the latest github release.

**Comment by bmaranville** [comment] 2021-06-05 00:37
(1) is what we did before, and it's pretty straightforward.  We're only supporting a handful of versions (3.6-3.9 currently)
(3) numba is something to consider, pretty easy to start using.  Maintaining CUDA/CL is a big job.  Wasmer is not inherently parallel but many engines can be run in parallel, and it is not just python version independent but platform independent!  (also just a pip install)

**Comment by bmaranville** [comment] 2021-06-05 16:33
In the short term, @pkienzle  - should I adjust the actions scripts so that we generate versioned wheels, and then push out a quick new version 0.8.15?  The current version is pretty seriously broken because of this.

**Comment by bmaranville** [comment] 2021-06-06 23:12
I have generated wheels for WIndows, py36 through py39 on a NIST windows laptop, and can upload to pypi anytime.  I removed the broken "abi3" wheel from pypi already.

**Comment by pkienzle** [comment] 2021-06-07 18:58
A v0.8.15 release is appropriate. The main new feature (assuming we unpin periodictable) is that we use energy dependent Gd for monochromatic sources. I think the bugs related to the change in periodictable interface have been fixed now (#122), both for polarized and unpolarized.

**Comment by pkienzle** [comment] 2021-06-07 19:01
You did the build by hand? I only see 3.8 mentioned in the [github action](https://github.com/reflectometry/refl1d/blob/master/.github/workflows/test.yml).

**Comment by bmaranville** [comment] 2021-06-07 19:06
Yes, by hand.
________________________________

**Comment by bmaranville** [comment] 2021-06-07 19:08
I have come to appreciate the venv package.  I install a particular version of python in a folder (not system-wide) then call e.g. .\py37\python.exe -m venv env_refl1d_37

Then I can activate that venv and pip install all the things.
________________________________

**Comment by bmaranville** [comment] 2021-06-07 19:11
Before release, we may have to roll back the feature of recalculating the Q range on PolarizedNeutronProbe when theta_offsets change - it is currently broken.  I have spent a few days on it and I am stuck.  There is a comment attached to one of the commits in that pull request.

________________________________

**Comment by pkienzle** [comment] 2021-06-07 19:14
I'm not seeing a PR for this, or a branch.

**Comment by bmaranville** [comment] 2021-06-07 19:30
I merged it after we discussed it... now I would say prematurely.

**Comment by bmaranville** [comment] 2021-06-13 15:31
Windows wheels have been added to version 0.8.14 on pypi.  The build script has been modified to make separate wheels for python 3.6 - 3.9 on Windows and 3.7 - 3.9 on MacOS, in preparation for the next release.

**Comment by pkienzle** [comment] 2021-06-13 18:30
Thanks!

**Comment by bmaranville** [comment] 2021-10-04 23:50
Release 0.8.15 will not need binary wheels.  It will be built with a numba dependency, which does JIT compiling of the things that need it.

**Closed by bmaranville** 2021-10-04 23:50 UTC
